<?php

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('settings')->delete();

        \DB::table('settings')->insert(array (
            0 =>
            array (
                'id' => 1,
                'key' => 'page_name',
                'name' => 'Page Name',
                'description' => 'Name of the page',
                'value' => 'GamePort',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'general',
                'reorder' => 1,
                'created_at' => NULL,
                'updated_at' => '2017-01-09 13:36:33',
            ),
            1 =>
            array (
                'id' => 2,
                'key' => 'meta_description',
                'name' => 'Meta Description',
                'description' => 'Meta Description',
                'value' => 'GamePort is the best place to sell, buy or trade your favourite video games. Join thousands of gamers from all over the world!',
                'field' => '{"name":"value","label":"Value","type":"textarea"}',
                'active' => 1,
                'category' => 'general',
                'reorder' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'key' => 'contact_email',
                'name' => 'Contact eMail',
                'description' => 'Contact eMail',
                'value' => 'admin@gameport.com',
                'field' => '{"name":"value","label":"Value","type":"email"}',
                'active' => 1,
                'category' => 'general',
                'reorder' => 4,
                'created_at' => NULL,
                'updated_at' => '2017-01-09 17:04:50',
            ),
            3 =>
            array (
                'id' => 4,
                'key' => 'logo',
                'name' => 'Logo',
                'description' => 'Logo',
                'value' => 'img/logo.png',
                'field' => '{"name":"value","label":"Value","type":"image_settings","upload":"true","hint":"min-height: 80px, transparent background. Retina logo will be generated automatically."}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 1,
                'created_at' => NULL,
                'updated_at' => '2017-01-19 22:39:51',
            ),
            4 =>
            array (
                'id' => 5,
                'key' => 'css',
                'name' => 'Additional CSS',
                'description' => 'css',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"textarea"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'key' => 'currency',
                'name' => 'Currency',
                'description' => 'currency',
                'value' => 'EUR',
                'field' => '{"name":"value","label":"Value","type":"select"}',
                'active' => 2,
                'category' => 'localization',
                'reorder' => 1,
                'created_at' => NULL,
                'updated_at' => '2017-01-19 22:31:01',
            ),
            6 =>
            array (
                'id' => 7,
                'key' => 'giantbomb_key',
                'name' => 'Giantbomb API Key',
                'description' => 'Giantbomb API Key',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'game',
                'reorder' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'key' => 'automatic_genres',
                'name' => 'Add new genres automatically',
                'description' => 'Add new genres automatically',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'game',
                'reorder' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'key' => 'date_format',
                'name' => 'Date Format',
                'description' => 'Date Format',
                'value' => 'Y-m-d',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'localization',
                'reorder' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'key' => 'time_format',
                'name' => 'Time Format',
                'description' => 'Time Format',
                'value' => 'H:i:s',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'localization',
                'reorder' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'key' => 'facebook_client_id',
                'name' => 'Facebook App-ID',
                'description' => 'facebook_client_id',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 3,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 19:11:47',
            ),
            11 =>
            array (
                'id' => 12,
                'key' => 'facebook_client_secret',
                'name' => 'Facebook App Secret-Key',
                'description' => 'facebook_client_secret',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 4,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 19:10:16',
            ),
            12 =>
            array (
                'id' => 13,
                'key' => 'user_confirmation',
                'name' => 'User need to confirm eMail',
                'description' => 'user_confirmation',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'key' => 'twitter_client_id',
                'name' => 'Twitter Consumer Key',
                'description' => 'twitter_client_id',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 6,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 18:48:20',
            ),
            14 =>
            array (
                'id' => 15,
                'key' => 'twitter_client_secret',
                'name' => 'Twitter Secret Key',
                'description' => 'twitter_client_secret',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 7,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 18:48:20',
            ),
            15 =>
            array (
                'id' => 16,
                'key' => 'google_client_id',
                'name' => 'Google Client-ID',
                'description' => 'google_client_id',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 9,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 19:25:11',
            ),
            16 =>
            array (
                'id' => 17,
                'key' => 'google_client_secret',
                'name' => 'Google Secret-ID',
                'description' => 'google_client_secret',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 10,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 19:25:11',
            ),
            17 =>
            array (
                'id' => 18,
                'key' => 'facebook_auth',
                'name' => 'Enable Facebook Auth',
                'description' => 'facebook_auth',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 2,
                'created_at' => NULL,
                'updated_at' => '2017-01-19 22:31:09',
            ),
            18 =>
            array (
                'id' => 19,
                'key' => 'twitter_auth',
                'name' => 'Enable Twitter Auth',
                'description' => 'twitter_auth',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 5,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 19:21:27',
            ),
            19 =>
            array (
                'id' => 20,
                'key' => 'google_auth',
                'name' => 'Enable Google Auth',
                'description' => 'google_auth',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => 8,
                'created_at' => NULL,
                'updated_at' => '2017-01-17 19:21:21',
            ),
            20 =>
            array (
                'id' => 21,
                'key' => 'sub_title',
                'name' => 'Sub Title',
                'description' => 'Sub Title',
                'value' => 'Trade, sell or buy your favourite video games!',
                'field' => '{"name":"value","label":"Value","type":"text"}
',
                'active' => 1,
                'category' => 'general',
                'reorder' => 2,
                'created_at' => NULL,
                'updated_at' => '2017-01-18 18:29:13',
            ),
            21 =>
            array (
                'id' => 22,
                'key' => 'facebook_link',
                'name' => 'Facebook Link',
                'description' => NULL,
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}
',
                'active' => 1,
                'category' => 'design',
                'reorder' => 5,
                'created_at' => NULL,
                'updated_at' => '2017-01-21 21:20:03',
            ),
            22 =>
            array (
                'id' => 23,
                'key' => 'twitter_link',
                'name' => 'Twitter Link',
                'description' => NULL,
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}
',
                'active' => 1,
                'category' => 'design',
                'reorder' => 6,
                'created_at' => NULL,
                'updated_at' => '2017-01-21 21:20:13',
            ),
            23 =>
            array (
                'id' => 24,
                'key' => 'google_plus_link',
                'name' => 'Google Plus Link',
                'description' => NULL,
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 7,
                'created_at' => NULL,
                'updated_at' => '2017-01-21 21:20:13',
            ),
            24 =>
            array (
                'id' => 25,
                'key' => 'youtube_link',
                'name' => 'YouTube Link',
                'description' => NULL,
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 8,
                'created_at' => NULL,
                'updated_at' => '2017-01-21 21:20:13',
            ),
            25 =>
            array (
                'id' => 26,
                'key' => 'favicon',
                'name' => 'Favicon',
                'description' => NULL,
                'value' => 'img/favicon-32x32.png',
                'field' => '{"name":"value","label":"Value","type":"image_settings","upload":"true","hint":"32x32 png, transparent background allowed. 16x16 icon will be generated automatically."}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'key' => 'default_locale',
                'name' => 'Default Language',
                'description' => 'test',
                'value' => 'en',
                'field' => '{"name":"value","label":"Value","type":"select"}',
                'active' => 1,
                'category' => 'localization',
                'reorder' => 5,
                'created_at' => NULL,
                'updated_at' => '2017-01-22 13:39:51',
            ),
            27 =>
            array (
                'id' => 28,
                'key' => 'platform_logo',
                'name' => 'Use platform logos instead of simple text',
                'description' => NULL,
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"You can download all platform logos on wiledia.com."}',
                'active' => 1,
                'category' => 'game',
                'reorder' => 3,
                'created_at' => NULL,
                'updated_at' => '2017-01-22 13:12:57',
            ),
            28 =>
            array (
                'id' => 29,
                'key' => 'js',
                'name' => 'Additional JS',
                'description' => 'JS',
                'value' => NULL,
                'field' => '{"name":"value","label":"Value","type":"textarea"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'key' => 'locale_selector',
                'name' => 'Locale Selector',
                'description' => 'Locale Selector',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"User can select language in frontend."}',
                'active' => 1,
                'category' => 'localization',
                'reorder' => 4,
                'created_at' => NULL,
                'updated_at' => '2017-01-22 13:40:08',
            ),
            30 =>
            array (
                'id' => 31,
                'key' => 'frontpage_carousel',
                'name' => 'New releases carousel on frontpage',
                'description' => 'New releases carousel on frontpage',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'key' => 'google_maps_key',
                'name' => 'Google Maps API Key',
                'description' => 'Google Maps API Key',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'localization',
                'reorder' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'key' => 'frontpage_carousel_day',
                'name' => 'Release in max',
                'description' => 'Release in max',
                'value' => '21',
                'field' => '{"name":"value","label":"Value","type":"number","suffix":"Days","hint":"This change can take a few minutes."}',
                'active' => 1,
                'category' => 'design',
                'reorder' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'key' => 'google_adsense',
                'name' => 'Enable Google AdSense',
                'description' => 'Enable Google AdSense',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'ads',
                'reorder' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'key' => 'google_adsense_code',
                'name' => 'Google AdSense Code',
                'description' => 'Google AdSense Code',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"textarea","hint":"Best results with responsive ads"}',
                'active' => 1,
                'category' => 'ads',
                'reorder' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'key' => 'buy_button_ref',
                'name' => 'Enable Buy Buttton Ref Link',
                'description' => 'Enable Buy Buttton Ref Link',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'ads',
                'reorder' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'key' => 'buy_button_ref_merchant',
                'name' => 'Buy Button Merchant',
                'description' => 'Buy Button Merchant',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text","hint":"For example: Amazon"}',
                'active' => 1,
                'category' => 'ads',
                'reorder' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'key' => 'buy_button_ref_link',
                'name' => 'Buy Button Link',
                'description' => 'Buy Button Link',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text","hint":"Add %game_name% to include current game name in the link"}',
                'active' => 1,
                'category' => 'ads',
                'reorder' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'key' => 'script_version',
                'name' => 'script_version',
                'description' => 'script_version',
                'value' => '1.5',
                'field' => '',
                'active' => 1,
                'category' => '',
                'reorder' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'key' => 'location_api',
                'name' => 'Location API',
                'description' => 'location_api',
                'value' => 'zippopotam',
                'field' => '{"name":"value","label":"Value","type":"select","hint":"Location API for the location feature."}',
                'active' => 1,
                'category' => 'localization',
                'reorder' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'key' => 'picture_upload',
                'name' => 'Enable Picture Upload',
                'description' => 'picture_upload',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'listing',
                'reorder' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'key' => 'watermark',
                'name' => 'Picture Watermark',
                'description' => 'watermark',
                'value' => 'img/watermark.png',
                'field' => '{"name":"value","label":"Value","type":"image_settings","upload":"true","hint":"png with transparent background."}',
                'active' => 1,
                'category' => 'listing',
                'reorder' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'key' => 'ssl',
                'name' => 'Force HTTPS (SSL)',
                'description' => 'ssl',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'general',
                'reorder' => '5',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),



            43 =>
            array (
                'id' => 44,
                'key' => 'decimal_place',
                'name' => 'Show decimal places on even numbers',
                'description' => 'decimal_place',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"Example for disabled option: 16.00 will be displayed as 16"}',
                'active' => 1,
                'category' => 'listing',
                'reorder' => '3',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'key' => 'recaptcha_register',
                'name' => 'Enable invisible reCAPTCHA for registration',
                'description' => 'recaptcha_register',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 11,
                'category' => 'auth',
                'reorder' => '11',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'key' => 'recaptcha_secret',
                'name' => 'reCAPTCHA Secret',
                'description' => 'recaptcha_secret',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => '12',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'key' => 'recaptcha_sitekey',
                'name' => 'reCAPTCHA Site Key',
                'description' => 'recaptcha_sitekey',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => '13',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'key' => 'distance_unit',
                'name' => 'Distance unit',
                'description' => 'distance_unit',
                'value' => 'km',
                'field' => '{"name":"value","label":"Value","type":"select_from_array","hint":"Unit for the distance between user and listing."}',
                'active' => 1,
                'category' => 'listing',
                'reorder' => '4',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'key' => 'payment',
                'name' => 'Enable Payment System',
                'description' => 'payment',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'key' => 'variable_fee',
                'name' => 'Variable fee',
                'description' => 'variable_fee',
                'value' => '8',
                'field' => '{"name":"value","label":"Value","type":"number","hint":"Fee for successful transaction in percentage","prefix":"%"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'key' => 'fixed_fee',
                'name' => 'Fixed fee',
                'description' => 'fixed_fee',
                'value' => '0.35',
                'field' => '{"name":"value","label":"Value","type":"text","hint":"[Format: 0.00] Fixed fee for successful transaction in your site currency","prefix":"site_currency"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '3',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'key' => 'paypal_sandbox',
                'name' => 'PayPal Sandbox Mode',
                'description' => 'paypal_sandbox',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '4',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'key' => 'paypal_client_id',
                'name' => 'PayPal Client-ID',
                'description' => 'paypal_client_id',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '5',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'key' => 'paypal_client_secret',
                'name' => 'PayPal Secret Key',
                'description' => 'paypal_client_secret',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '6',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'key' => 'comment_game',
                'name' => 'Game Comments',
                'description' => 'comment_game',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'comment',
                'reorder' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'key' => 'comment_listing',
                'name' => 'Listing Comments',
                'description' => 'comment_listing',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'comment',
                'reorder' => '2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'key' => 'comment_article',
                'name' => 'Article Comments',
                'description' => 'comment_article',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'comment',
                'reorder' => '3',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'key' => 'comment_max_page',
                'name' => 'Max comments per page',
                'description' => 'comment_max_page',
                'value' => '15',
                'field' => '{"name":"value","label":"Value","type":"number"}',
                'active' => 1,
                'category' => 'comment',
                'reorder' => '4',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'key' => 'comment_throttle',
                'name' => 'Throttle flood',
                'description' => 'comment_throttle',
                'value' => '20',
                'field' => '{"name":"value","label":"Value","type":"number","hint":"Time in seconds between two comments for a user.","prefix":"sec"}',
                'active' => 1,
                'category' => 'comment',
                'reorder' => '5',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'key' => 'locate_position',
                'name' => 'Locate guest position for distance to listing',
                'description' => 'locate_position',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'localization',
                'reorder' => '6',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'key' => 'instagram_link',
                'name' => 'Instagram Link',
                'description' => 'instagram_link',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => '8',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 =>
            array (
                'id' => 62,
                'key' => 'stripe_client_id',
                'name' => 'Stripe Publishable Key',
                'description' => 'stripe_client_id',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '9',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 =>
            array (
                'id' => 63,
                'key' => 'stripe_client_secret',
                'name' => 'Stripe Secret Key',
                'description' => 'stripe_client_secret',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '8',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 =>
            array (
                'id' => 64,
                'key' => 'paypal',
                'name' => 'PayPal',
                'description' => 'paypal',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '3',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 =>
            array (
                'id' => 65,
                'key' => 'stripe',
                'name' => 'Stripe',
                'description' => 'stripe',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '7',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 =>
            array (
                'id' => 66,
                'key' => 'minify_html',
                'name' => 'Minify HTML',
                'description' => 'minify_html',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'general',
                'reorder' => '6',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 =>
            array (
                'id' => 67,
                'key' => 'jpeg_quality',
                'name' => 'JPEG Quality',
                'description' => 'jpeg_quality',
                'value' => '80',
                'field' => '{"name":"value","label":"Value","type":"number","hint":"JPEG quality in percentage. Lower value to reduce image file size. [Default: 80]","prefix":"%"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => '11',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 =>
            array (
                'id' => 68,
                'key' => 'digital_downloads_only',
                'name' => 'User can only list digital downloads',
                'description' => 'digital_downloads_only',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"Pickup, delivery and condition option will be disabled."}',
                'active' => 1,
                'category' => 'listing',
                'reorder' => '5',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 =>
            array (
                'id' => 69,
                'key' => 'onesignal',
                'name' => 'Enable OneSignal Web Push Notifications',
                'description' => 'onesignal',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'notification',
                'reorder' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 =>
            array (
                'id' => 70,
                'key' => 'onesignal_app_id',
                'name' => 'OneSignal App ID',
                'description' => 'onesignal_app_id',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'notification',
                'reorder' => '2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 =>
            array (
                'id' => 71,
                'key' => 'onesignal_rest_api_key',
                'name' => 'OneSignal REST API Key',
                'description' => 'onesignal_rest_api_key',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'notification',
                'reorder' => '3',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 =>
            array (
                'id' => 72,
                'key' => 'onesignal_safari_web_id',
                'name' => 'OneSignal Safari Web ID',
                'description' => 'onesignal_safari_web_id',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text","hint":"Optional"}',
                'active' => 1,
                'category' => 'notification',
                'reorder' => '4',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 =>
            array (
                'id' => 73,
                'key' => 'twitch_auth',
                'name' => 'Enable Twitch Auth',
                'description' => 'twitch_auth',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => '14',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 =>
            array (
                'id' => 74,
                'key' => 'twitch_client_id',
                'name' => 'Twitch Client-ID',
                'description' => 'twitch_client_id',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => '15',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 =>
            array (
                'id' => 75,
                'key' => 'twitch_client_secret',
                'name' => 'Twitch Secret-ID',
                'description' => 'twitch_client_secret',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => '16',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 =>
            array (
                'id' => 76,
                'key' => 'steam_auth',
                'name' => 'Enable Steam Auth',
                'description' => 'steam_auth',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => '17',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 =>
            array (
                'id' => 77,
                'key' => 'steam_client_secret',
                'name' => 'Steam Secret-ID',
                'description' => 'steam_client_secret',
                'value' => '',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'auth',
                'reorder' => '18',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 =>
            array (
                'id' => 78,
                'key' => 'default_theme',
                'name' => 'Default Theme',
                'description' => 'default_theme',
                'value' => 'default',
                'field' => '{"name":"value","label":"Value","type":"text"}',
                'active' => 1,
                'category' => 'theme',
                'reorder' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 =>
            array (
                'id' => 79,
                'key' => 'theme_selector',
                'name' => 'Theme Selector',
                'description' => 'theme_selector',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"User can select theme in frontend."}',
                'active' => 1,
                'category' => 'design',
                'reorder' => '12',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 =>
            array (
                'id' => 80,
                'key' => 'payment_force',
                'name' => 'Force Payment System',
                'description' => 'payment_force',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"Force user to use the payment system."}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '10',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 =>
            array (
                'id' => 81,
                'key' => 'user_add_item',
                'name' => 'User can add new games through API',
                'description' => 'user_add_item',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"If disabled, only users with the edit_games permission will be able to add games through the API."}',
                'active' => 1,
                'category' => 'game',
                'reorder' => '4',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 =>
            array (
                'id' => 82,
                'key' => 'cookie_consent',
                'name' => 'Cookie consent',
                'description' => 'cookie_consent',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"Shows a notification that the site is using cookies."}',
                'active' => 1,
                'category' => 'legal',
                'reorder' => '4',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 =>
            array (
                'id' => 83,
                'key' => 'landing_page',
                'name' => 'Landing Page',
                'description' => 'landing_page',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"Enable landing page for guests."}',
                'active' => 1,
                'category' => 'design',
                'reorder' => '13',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 =>
            array (
                'id' => 84,
                'key' => 'withdrawal_paypal',
                'name' => 'Withdrawal PayPal',
                'description' => 'withdrawal_paypal',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"User can request a PayPal withdrawal."}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '11',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 =>
            array (
                'id' => 85,
                'key' => 'withdrawal_bank',
                'name' => 'Withdrawal Bank Transfer',
                'description' => 'withdrawal_bank',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"toggle","hint":"User can request a Bank Transfer withdrawal."}',
                'active' => 1,
                'category' => 'payment',
                'reorder' => '12',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 =>
            array (
                'id' => 86,
                'key' => 'register_checkbox',
                'name' => 'During registration user need to accept',
                'description' => 'register_checkbox',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"select","hint":"A checkbox will be displayed during registration."}',
                'active' => 1,
                'category' => 'legal',
                'reorder' => '1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 =>
            array (
                'id' => 87,
                'key' => 'terms_service',
                'name' => 'Terms of Service page',
                'description' => 'terms_service',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"select","hint":"The page name will be displayed in the frontend."}',
                'active' => 1,
                'category' => 'legal',
                'reorder' => '2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 =>
            array (
                'id' => 88,
                'key' => 'privacy_policy',
                'name' => 'Privacy Policy page',
                'description' => 'privacy_policy',
                'value' => '1',
                'field' => '{"name":"value","label":"Value","type":"select","hint":"The page name will be displayed in the frontend."}',
                'active' => 1,
                'category' => 'legal',
                'reorder' => '3',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 =>
            array (
                'id' => 89,
                'key' => 'landing_image',
                'name' => 'Landing Page Image',
                'description' => 'landing_image',
                'value' => 'img/landing.jpg',
                'field' => '{"name":"value","label":"Value","type":"image_settings","upload":"true"}',
                'active' => 1,
                'category' => 'design',
                'reorder' => '14',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 =>
            array (
                'id' => 90,
                'key' => 'landing_game',
                'name' => 'Landing Page Game',
                'description' => 'landing_game',
                'value' => '0',
                'field' => '{"name":"value","label":"Value","type":"text","hint":"ID of the game which will be displayed on the landing page [0 = Disabled]."}',
                'active' => 1,
                'category' => 'design',
                'reorder' => '15',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));


    }
}
